#!/bin/sh
if [ -d ~/Repos/personal/e-comments ]; then
    cp ~/Repos/personal/e-comments/client/js/* input/js
    cp ~/Repos/personal/e-comments/client/css/e-comments.css input/css/c.in
    cd input/css && make
    exit 0
else
    echo "Do you have e-comments locally?"
    exit 1
fi
